# File: docker-compose.yml
# This file defines how Docker should run your multi-container application.
# Place this file in the ROOT of your osint-crm project (parent to frontend and backend folders).

# The 'version' attribute is no longer strictly necessary for most modern Docker Compose versions.
# version: '3.8'

services:
  # Frontend Service (React App served by Nginx)
  frontend:
    build:
      context: ./frontend # Path to the frontend Dockerfile and source code
      dockerfile: Dockerfile # Assumes Dockerfile is in the frontend directory
    container_name: osint-crm-frontend
    ports:
      - "8080:80" # Map port 8080 on host to port 80 in container (Nginx default)
    restart: unless-stopped
    depends_on:
      - backend # Ensures backend starts before frontend (optional, but good practice)
    networks:
      - osint-crm-network

  # Backend Service (Node.js/Express API)
  backend:
    build:
      context: ./backend # Path to the backend Dockerfile and source code
      dockerfile: Dockerfile # Assumes Dockerfile is in the backend directory
    container_name: osint-crm-backend
    ports:
      - "3001:3001" # Map port 3001 on host to port 3001 in container
    environment:
      # Environment variables for the backend
      NODE_ENV: development # or production
      PORT: 3001
      # Database connection details (will be used by server.js)
      DB_HOST: db # This 'db' matches the service name of our postgres container
      DB_USER: ${DB_USER:-postgres} # Use environment variable or default
      DB_PASSWORD: ${DB_PASSWORD:-changeme} # Use environment variable or default - CHANGE THIS!
      DB_NAME: ${DB_NAME:-osint_crm_db}
      DB_PORT: 5432
    volumes:
      - ./backend:/usr/src/app # Mounts your local backend code into the container for development (optional)
      - /usr/src/app/node_modules # Anonymous volume to prevent local node_modules from overwriting container's
    restart: unless-stopped
    depends_on:
      - db # Ensures database starts before the backend
    networks:
      - osint-crm-network

  # Database Service (PostgreSQL)
  db:
    image: postgres:15-alpine # Use official PostgreSQL image
    container_name: osint-crm-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme} # CHANGE THIS IN YOUR ENVIRONMENT
      POSTGRES_DB: ${DB_NAME:-osint_crm_db}
    ports:
      - "5432:5432" # Map port 5432 on host to port 5432 in container (PostgreSQL default)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
    restart: unless-stopped
    networks:
      - osint-crm-network

# Define a network for the services to communicate
networks:
  osint-crm-network:
    driver: bridge

# Define a named volume for persistent PostgreSQL data
volumes:
  postgres_data:
